### ISSUE TITLE
Sublime 3?

### ISSUE THREAD

**Issue by gingerbeardman** [TheTwitchy/BookmarkStack#3]
Do you plan to make this compatible?

**Comment by TheTwitchy** [comment]
Hi @gingerbeardman, this should already be SublimeText 3.X compatible. Just checked myself, and I'm currently running 3.0 build 3143 with this plugin enabled. Are you getting any errors or what is not working?

**Comment by gingerbeardman** [comment]
Ah, I was looking in package control.

**Comment by gingerbeardman** [comment]
Installed and working, thanks!
